plugins:
  word_cloud_enabled:
    type: bool
    default: true
    client: true
  word_cloud_set_size:
    default: 300
    max: 1000
    min: 50
    client: false
  word_cloud_minimum_length:
    default: 3
    client: false
  word_cloud_exclude_symbols:
    type: bool
    default: true
    client: false
  word_cloud_include_mentions:
    type: bool
    default: false
    client: false
