plugins:
  word_cloud_enabled:
    type: bool
    default: true
    client: true
  word_cloud_source_categories:
    default: ''
    type: category_list
    client: false
  word_cloud_set_size:
    default: 300
    max: 1000
    min: 50
    client: false
  word_cloud_minimum_length:
    default: 3
    max: 10
    min: 0
    client: false
  word_cloud_ignore_portion:
    default: 300
    max: 300
    min: 0
    client: false
